name: Run Tests

on: workflow_dispatch
jobs:
#   test:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#       - name: Set up Python
#         uses: actions/setup-python@v4
#       - name: Install dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install -r requirements.txt;
#       - name: Run Tests
#         run: pytest
  deploy:
    # needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: appleboy/ssh-action@v1.0.0
        with:
          host: 159.223.30.198
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            pwd
            ls
     
       
